server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: none
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
