server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    jpa:
      hibernate:
        ddl-auto: none
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
