server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://103.191.208.62:3306/errbowoc_gobarts_user_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: errbowoc_firo
    password: "#Goboli180"
    jpa:
      hibernate:
        ddl-auto: none
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
